// Domain mappings. Most companies are derived automatically from their domain;
// this file overrides the auto-derived name only where the mapping isn't obvious,
// or where multiple domains should roll up to one company (e.g. doehler.com +
// doehler.com.br → "Döhler").
//
// Personal-mail domains and ISPs are excluded entirely.

export const PERSONAL_DOMAINS = new Set([
  "gmail.com", "googlemail.com",
  "yahoo.com", "yahoo.com.br", "yahoo.co.uk", "yahoo.es", "yahoo.fr",
  "yahoo.de", "yahoo.gr", "yahoo.in", "yahoo.com.ar", "yahoo.com.tr",
  "ymail.com", "myyahoo.com",
  "hotmail.com", "hotmail.fr", "hotmail.de", "hotmail.co.uk", "hotmail.es", "hotmail.it",
  "outlook.com", "outlook.fr", "outlook.de", "outlook.es",
  "icloud.com", "me.com", "mac.com",
  "msn.com", "aol.com",
  "live.com", "live.nl", "live.it",
  "web.de", "gmx.de", "gmx.com", "gmx.net", "t-online.de",
  "mail.ru", "yandex.ru", "rediffmail.com",
  "uol.com.br", "terra.com.br", "bol.com.br",
  "telenet.be", "comcast.net", "sbcglobal.net", "cs.com",
  "kpnmail.nl", "hetnet.nl", "ziggo.nl",
  "email.cz", "inbox.lv", "swissonline.ch",
  "daum.net", "naver.com",
  "newsfeed.email", "office.net",
  "tampabay.rr.com", "students.wcpss.net", "edu.lohja.fi",
  "mailmt.com", "goodpostman.com", "eaglesmail.net",
  "qq.com", "163.com", "126.com", "sina.com", "sina.cn",
  "free.fr", "orange.fr", "wanadoo.fr", "laposte.net",
  "btinternet.com", "sky.com", "talktalk.net", "virginmedia.com",
]);

// Domain → display name. Use this when:
//  - the domain doesn't obviously map to the company name
//  - multiple domains should merge into one company
//  - the auto-derived name would be ugly (e.g. "Iff" instead of "IFF")
export const DOMAIN_TO_COMPANY = {
  // Flavour and ingredient houses
  "doehler.com": "Döhler",
  "doehler.com.br": "Döhler",
  "doehler.co.in": "Döhler",
  "doehler.co.nz": "Döhler",
  "iff.com": "IFF",
  "frutarom.com": "IFF (Frutarom)",
  "isobionics.com": "IFF (Isobionics)",
  "treatt.com": "Treatt",
  "givaudan.com": "Givaudan",
  "firmenich.com": "Firmenich",
  "dsm-firmenich.com": "DSM-Firmenich",
  "symrise.com": "Symrise",
  "mane.com": "Mane",
  "takasago.com": "Takasago",
  "robertet.com": "Robertet",
  "robertetusa.com": "Robertet",
  "kerry.com": "Kerry",
  "natara-global.com": "Natara",
  "guedant.com": "Guedant",
  "bontoux.com": "Bontoux",
  "moellhausen.com": "Moellhausen",
  "esarom.com": "Esarom",
  "lebermuth.com": "Lebermuth",
  "ungerer.co.uk": "Ungerer",
  "berjeinc.com": "Berjé",
  "synergytaste.com": "Synergy Flavors",
  "globalessence.com": "Global Essence",
  "callisons.com": "Callison",
  "citrusandallied.com": "Citrus & Allied",
  "flavormaterials.com": "Flavor Materials",
  "carriere.de": "Carrière",
  "lionelhitchen.com": "Lionel Hitchen",
  "lheo.co.uk": "Lionel Hitchen",
  "turpaz-group.com": "Turpaz",

  // Juice processors & traders
  "citrofrut.com": "Citrofrut",
  "citromax.com": "Citromax",
  "citromax.com.ar": "Citromax",
  "citroil.com": "Citromax",
  "citrosuco.com": "Citrosuco",
  "citrosuco.com.br": "Citrosuco",
  "biocitrus.com.br": "Citrosuco (Biocitrus)",
  "cutrale.com": "Cutrale",
  "ldc.com": "Louis Dreyfus Company",
  "ldcom.com": "Louis Dreyfus Company",
  "refresco.com": "Refresco",
  "tropicana.com": "Tropicana",
  "capri-sun.com": "Capri-Sun",
  "fritz-kola.com": "Fritz-Kola",
  "floridasnatural.com": "Florida's Natural",
  "perriconefarms.com": "Perricone Farms",
  "sunorchard.com": "Sun Orchard",
  "brothersinternational.com": "Brothers International",
  "greenwoodassociates.com": "Greenwood Associates",
  "misitanoestracuzzi.com": "Misitano & Stracuzzi",
  "ganshmuel.com": "Gan Shmuel",
  "trisun.co.il": "Trisun",
  "fgftrapani.com": "FGF Trapani",
  "fgftrapani.com.ar": "FGF Trapani",
  "lassonde.com": "Lassonde",
  "welchs.com": "Welch's",
  "wonderful.com": "Wonderful Company",
  "agroterenas.com.br": "Agroterenas",
  "sucorrico.com.br": "Sucorrico",
  "primor.ind.br": "Primor",
  "prodalim.com": "Prodalim",
  "icegen.com": "Icegen",
  "svz.com": "SVZ",
  "miritz.de": "Miritz",
  "miritz.com": "Miritz",
  "eckes-granini.com": "Eckes-Granini",
  "agrana.com": "AGRANA",
  "riedel.nl": "Riedel",
  "labojuice.com": "Labojuice",
  "fruity-line.nl": "Fruity-Line",
  "oranka.co.uk": "Oranka",
  "oranka.nl": "Oranka",
  "hero.es": "Hero",
  "hero.nl": "Hero",
  "konings.be": "Konings",
  "spindriftfresh.com": "Spindrift",
  "drinkspindrift.com": "Spindrift",
  "fever-tree.com": "Fevertree",
  "ticofrut.com": "Ticofrut",
  "lufussa.com": "Lufussa",
  "alicoinc.com": "Alico",
  "fwwcitrus.com": "FWW Citrus",
  "icccitrus.com": "ICC Industries",
  "brown-intl.com": "Brown International",

  // Beverage giants & retailers
  "coca-cola.com": "The Coca-Cola Company",
  "ccep.com": "Coca-Cola Europacific Partners",
  "ccep.eu": "Coca-Cola Europacific Partners",
  "pepsico.com": "PepsiCo",
  "adm.com": "ADM",
  "cargill.com": "Cargill",
  "anheuser-busch.com": "Anheuser-Busch InBev",
  "inbevcapital.com": "AB InBev Capital",
  "brewdog.com": "BrewDog",
  "sunopta.com": "SunOpta",
  "oceanspray.com": "Ocean Spray",
  "in.nestle.com": "Nestlé",
  "us.nestle.com": "Nestlé",
  "kroger.com": "Kroger",
  "heb.com": "H-E-B",
  "doleintl.com": "Dole",
  "dole.com": "Dole",
  "effem.com": "Mars",
  "treetop.com": "Tree Top",

  // Packaging, equipment, services
  "tetrapak.com": "Tetra Pak",
  "elopak.com": "Elopak",
  "alfalaval.com": "Alfa Laval",
  "jbtc.com": "JBT Corporation",
  "oxbo.com": "Oxbo",
  "elementar.com": "Elementar",
  "biomerieux.com": "bioMérieux",
  "abenzymes.com": "AB Enzymes",
  "bucheralimentech.com": "Bucher Alimentech",
  "zumex.com": "Zumex",
  "solenis.com": "Solenis",
  "lanxess.com": "LANXESS",
  "kraftchemical.com": "Kraft Chemical",
  "dow.com": "Dow",
  "rahn-group.com": "Rahn Group",

  // Finance & professional services
  "stonex.com": "StoneX",
  "rjobrien.com": "RJ O'Brien",
  "barings.com": "Barings",
  "trivest.com": "Trivest",
  "paipartners.com": "PAI Partners",
  "haloinvesting.com": "Halo Investing",
  "bain.com": "Bain & Company",

  // Universities & research
  "ufl.edu": "University of Florida",
  "ucr.edu": "UC Riverside",
  "usf.edu": "University of South Florida",
  "butler.edu": "Butler University",
  "tamuk.edu": "Texas A&M Kingsville",
  "ag.arizona.edu": "University of Arizona",
  "nas.edu": "National Academies",

  // Industry bodies & government
  "citrus.myflorida.com": "Florida Dept. of Citrus",
  "freshfromflorida.com": "Florida Dept. of Agriculture",
  "ffva.com": "Florida Fruit & Vegetable Assn",
  "thecpso.org": "Citrus Producers' Steering Org.",
  "cga.co.za": "Citrus Growers' Assn. (S. Africa)",
  "ific.org": "IFIC",
  "nvdmc.org": "Florida Citrus Mutual",
  "afius.org": "AFI",
  "aijn.eu": "AIJN",
  "sgf.org": "SGF International",
  "ifu-fruitjuice.com": "IFU",

  // Media & data
  "datagro.com": "DATAGRO",
  "euromonitor.com": "Euromonitor",
  "marketsandmarkets.com": "MarketsandMarkets",
  "fruitnet.com": "Fruitnet",
  "tomatonews.com": "Tomato News",
  "confructa-medien.com": "confructa medien",
  "fruitjuicefocus.com": "Fruit Juice Focus",

  // Japan & APAC
  "mcfoods.co.jp": "Mitsubishi Foods",
  "morimura.co.jp": "Morimura Bros",
  "suntory.co.jp": "Suntory",
  "t-hasegawa.co.jp": "T. Hasegawa",
  "thasegawa.com": "T. Hasegawa",
  "itc.in": "ITC Limited",
  "ggpc.co.id": "Great Giant Pineapple",
  "ititropicals.com": "iTi Tropicals",
  "neonecreation.co.jp": "Neone Creation",
  "inatrading.jp": "Ina Trading",

  // Other notable mappings
  "kellencompany.com": "Kellen",
  "tradinorganic.com": "Tradin Organic",
  "exportpackers.com": "Export Packers",
  "duasrodas.com": "Duas Rodas",
  "letaba.com": "Letaba Citrus",
  "moutoncitrus.co.za": "Mouton Citrus",
  "summerpride.co.za": "Summerpride",
  "aeciworld.com": "AECI",
  "lycored.com": "Lycored",
  "cvista.com": "C-Vista",
  "ec2.com": "EC2",
};
